### ISSUE TITLE
Current height and target height stopped working with esphome 2023.2.x

### ISSUE THREAD

**Issue by paularmstrong** [tjhorner/esphome-standing-desk#4]
Ever since an upgrade during the month of February from esphome 2023.1.x to 2023.2.x, my fully jarvis desk has been reporting "NA" for the current height and setting the target height to any value sends the desk up to its max height.

I've tried a fresh build and flashing of the hardware, but receive the same results. Is this just me having a weird issue?

I'm not sure where to start debugging. Any help appreciated.

**Comment by tjhorner** [comment]
I've seen this kind of issue before, and it's usually fixed by restarting the desk's control box entirely. Try unplugging it for around 15 seconds then plug it back in.

My working theory is that sometimes the control box can get into a weird state where it no longer reports the current height in the way that the firmware expects, but I haven't been able to verify how that actually happens because I don't have a Jarvis desk

**Comment by paularmstrong** [comment]
I tried this and I have the same results. I unplugged everything, let it sit for 15-20 seconds, then plugged it all back in.

The desk went into ASR error mode, which requires it to be returned to as low as it can go by holding the DOWN button until it stops. After that, I have the same issue with NA reported height and any target change sends it all the way to the top.

**Comment by paularmstrong** [comment]
Did some digging and saw the VERY_VERBOSE logs within this repo, so I turned that on. Does this help at all? It's mostly just repeating the following:

```
[11:20:54][VV][standing_desk_height:027]: Reading byte: 180
[11:20:54][VV][standing_desk_height:027]: Reading byte: 1
[11:20:54][VV][standing_desk_height:027]: Reading byte: 1
[11:20:54][VV][standing_desk_height:027]: Reading byte: 1
```
[logs_pauls-standing-desk_run(1).txt](https://github.com/tjhorner/esphome-standing-desk/files/10854034/logs_pauls-standing-desk_run.1.txt)

**Comment by tjhorner** [comment]
Thank you for the logs! When you captured those, were you moving your desk?

Also: Which keypad do you use with your desk? If it has a display, does the current height show up there?

Also also: Can you make sure the decoder is set properly in the [configuration](https://upsy-desky.tjhorner.dev/docs/configuration/)?

**Comment by paularmstrong** [comment]
Yep, I was holding the up/down buttons. Here's an update in which I've pressed both up/down, presets 1, and 4 (kind of hard to figure out which is which, but they do differ like 184, 181, 164, 167, 176, 179)

[logs_pauls-standing-desk_run(4).txt](https://github.com/tjhorner/esphome-standing-desk/files/10864528/logs_pauls-standing-desk_run.4.txt)

I don't see any sort of configuration like the linked docs show…

<img width="1044" alt="Screenshot 2023-03-01 at 10 47 43" src="https://user-images.githubusercontent.com/33297/222235915-b72b6006-fe0f-44f0-8817-7ceb39e49a1d.png">

**Comment by paularmstrong** [comment]
Here's my esphome config (this is the original/first version hardware, btw):

```yaml
substitutions:
  device_name: pauls-standing-desk
  device_friendly_name: Paul’s standing desk

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  desk_config: github://tjhorner/esphome-standing-desk/configs/desks/fully_jarvis.yaml
  device_base: !include common/base.yaml

esphome:
  name: "pauls-standing-desk"
  platform: ESP8266
  board: d1_mini
```

And the `common/base.yaml`
```yaml
esphome:
  name: ${device_name}

wifi:
  // redacted

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
```
