### ISSUE TITLE
pin 13 and pin 15 incorrectly sets allow_other_uses: true

### ISSUE THREAD

**Issue by paularmstrong** [tjhorner/esphome-standing-desk#7]
Since 2023.12.x, I've been unable to update my esphome firmware with the following error:

```
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/pauls-standing-desk.yaml...
INFO Detected timezone 'America/Los_Angeles'
Failed config

output.gpio: [source <unicode string>:24]
  
  Pin 13 incorrectly sets allow_other_uses: true.
  platform: gpio
  inverted: True
  id: standing_desk_up_pin
  pin: 
    number: 13
    allow_other_uses: True
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
      analog: False
    inverted: False
output.gpio: [source <unicode string>:31]
  
  Pin 15 incorrectly sets allow_other_uses: true.
  platform: gpio
  inverted: True
  id: standing_desk_down_pin
  pin: 
    number: 15
    allow_other_uses: True
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
      analog: False
    inverted: False
```

Relevant configuration:

```yaml
substitutions:
  device_name: pauls-standing-desk
  device_friendly_name: Paul’s standing desk
  loglevel: ERROR

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  desk_config: github://tjhorner/esphome-standing-desk/configs/desks/uplift_v2.yaml
  device_base: !include common/base.yaml

esphome:
  name: "pauls-standing-desk"
  platform: ESP8266
  board: d1_mini
```
